# simpleEMS
# Copyright (C) 2026 Mohamoud Ali
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
Touchstone version 1 reader and writer for N-port S-parameters.

The writer emits real/imaginary (``RI``) data in hertz against a single
reference impedance, laid out exactly as scikit-rf 1.9.0 writes it so files
from older simpleEMS releases and new ones compare byte for byte. A 2-port
lists ``S11 S21 S12 S22`` on one line; 3 or more ports list the matrix row by
row, each row starting a new line and wrapping after four pairs. The reader
accepts any version-1 file with S-parameter data, in any frequency unit and
any of the ``RI``, ``MA`` and ``DB`` formats.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from pathlib import Path
from typing import NamedTuple

import numpy as np
from numpy.typing import ArrayLike, NDArray

from . import __version__

_REPOSITORY_URL = "https://github.com/MohamoudAli12/simpleEMS"
_PAIRS_PER_LINE = 4
_FREQUENCY_SCALE = {"HZ": 1.0, "KHZ": 1e3, "MHZ": 1e6, "GHZ": 1e9}
_DATA_FORMATS = {"RI", "MA", "DB"}


class TouchstoneData(NamedTuple):
    """
    S-parameters read from a Touchstone file.

    Attributes
    ----------
    freqs : NDArray
        Frequency points in Hz, shape ``(F,)``.
    s_matrix : NDArray
        Complex S-parameters, shape ``(F, P, P)``; ``s_matrix[:, i, j]``
        holds S(i+1)(j+1).
    ref_impedance : float
        Reference impedance in ohms shared by every port.
    """

    freqs: NDArray
    s_matrix: NDArray
    ref_impedance: float


def write_touchstone(
    path: str | Path,
    freqs: ArrayLike,
    s_matrix: ArrayLike,
    *,
    ref_impedance: float = 50.0,
    comment: str | None = None,
) -> Path:
    """
    Write S-parameters to a Touchstone ``.sNp`` file.

    Parameters
    ----------
    path : str or Path
        Output path without the extension; the writer appends ``.sNp``
        from the port count and creates missing parent directories.
    freqs : ArrayLike
        Frequency points in Hz, shape ``(F,)``.
    s_matrix : ArrayLike
        Complex S-parameters, shape ``(F, P, P)`` with ``s_matrix[:, i, j]``
        holding S(i+1)(j+1). A 1-D array of shape ``(F,)`` counts as a
        1-port.
    ref_impedance : float, optional
        Reference impedance in ohms for every port. Default is ``50.0``.
    comment : str, optional
        Text written as ``!`` comment lines at the top of the file.

    Returns
    -------
    Path
        The path of the written file.

    Raises
    ------
    ValueError
        If the matrix is not square per frequency, the frequency count does
        not match, or ``ref_impedance`` is not positive.
    """
    frequencies = np.asarray(freqs, dtype=float).ravel()
    matrix = np.asarray(s_matrix, dtype=complex)
    if matrix.ndim == 1:
        matrix = matrix[:, np.newaxis, np.newaxis]

    if matrix.ndim != 3 or matrix.shape[1] != matrix.shape[2]:
        raise ValueError(f"s_matrix must have shape (F, P, P); got {matrix.shape}")
    if matrix.shape[0] != frequencies.size:
        raise ValueError(
            f"{frequencies.size} frequencies but {matrix.shape[0]} S-matrices"
        )
    if ref_impedance <= 0:
        raise ValueError(f"ref_impedance must be positive; got {ref_impedance}")

    port_count = matrix.shape[1]
    output = Path(path)
    output = output.with_name(f"{output.name}.s{port_count}p")
    output.parent.mkdir(parents=True, exist_ok=True)

    lines = [f"!{text}" for text in (comment or "").splitlines()]
    lines.append(f"! Generated by simpleEMS {__version__} ({_REPOSITORY_URL}).")
    # The trailing space matches the files older releases wrote via scikit-rf.
    lines.append(f"# Hz S RI R {float(ref_impedance)!r} ")
    lines.extend(_column_labels(port_count))
    for frequency, frequency_matrix in zip(frequencies, matrix, strict=True):
        lines.extend(_data_lines(frequency, frequency_matrix))

    output.write_text("\n".join(lines) + "\n", newline="\n")
    return output


def read_touchstone(path: str | Path) -> TouchstoneData:
    """
    Read S-parameters from a Touchstone version 1 ``.sNp`` file.

    Parameters
    ----------
    path : str or Path
        File to read; the ``.sNp`` extension sets the port count.

    Returns
    -------
    TouchstoneData
        Frequencies in Hz, the complex ``(F, P, P)`` S-matrix and the
        reference impedance.

    Raises
    ------
    ValueError
        If the extension is not ``.sNp``, the file is Touchstone 2, holds
        parameters other than S, or its value count does not fill whole
        frequency records.
    """
    source = Path(path)
    extension = re.fullmatch(r"\.s(\d+)p", source.suffix.lower())
    if extension is None:
        raise ValueError(f"expected a .sNp file; got {source.name}")
    port_count = int(extension.group(1))

    # Spec defaults when the option line leaves a field out.
    frequency_unit, data_format, ref_impedance = "GHZ", "MA", 50.0
    option_line_seen = False
    numbers: list[float] = []

    for line in source.read_text().splitlines():
        content = line.split("!", 1)[0].strip()
        if not content:
            continue
        if content.startswith("["):
            raise ValueError("Touchstone 2 files are not supported")
        if content.startswith("#"):
            # The spec says to ignore every option line after the first.
            if not option_line_seen:
                frequency_unit, data_format, ref_impedance = _parse_option_line(content)
                option_line_seen = True
            continue
        numbers.extend(float(token) for token in content.split())

    record_length = 1 + 2 * port_count**2
    if not numbers or len(numbers) % record_length:
        raise ValueError(
            f"{len(numbers)} values do not fill whole {port_count}-port records"
        )

    records = np.array(numbers).reshape(-1, record_length)
    freqs = records[:, 0] * _FREQUENCY_SCALE[frequency_unit]
    values = _to_complex(records[:, 1::2], records[:, 2::2], data_format)
    s_matrix = values.reshape(-1, port_count, port_count)
    if port_count == 2:
        # The 2-port exception is column-major: S11 S21 S12 S22.
        s_matrix = s_matrix.transpose(0, 2, 1)

    return TouchstoneData(freqs, s_matrix, ref_impedance)


def _ordered_rows(matrix: NDArray) -> list[NDArray]:
    """Split one frequency's matrix into rows in Touchstone 1 order."""
    if matrix.shape[0] == 2:
        # The 2-port exception: one row, column-major, S11 S21 S12 S22.
        return [matrix.T.ravel()]
    return list(matrix)


def _wrapped(rows: list[NDArray]) -> list[Sequence]:
    """Break each row into lines of at most four pairs."""
    return [
        row[start : start + _PAIRS_PER_LINE]
        for row in rows
        for start in range(0, len(row), _PAIRS_PER_LINE)
    ]


def _column_labels(port_count: int) -> list[str]:
    """Comment lines naming each column, laid out like the data lines."""
    names = np.array(
        [
            [f"S{row}{column}" for column in range(1, port_count + 1)]
            for row in range(1, port_count + 1)
        ]
    )
    lines = [
        "".join(f" Re{name} Im{name}" for name in chunk)
        for chunk in _wrapped(_ordered_rows(names))
    ]
    return [f"!freq{lines[0]}", *(f"!{line}" for line in lines[1:])]


def _data_lines(frequency: float, matrix: NDArray) -> list[str]:
    """Format one frequency point as Touchstone 1 data lines."""
    lines = [
        "".join(f" {float(value.real)!r} {float(value.imag)!r}" for value in chunk)
        for chunk in _wrapped(_ordered_rows(matrix))
    ]
    lines[0] = f"{float(frequency)!r}{lines[0]}"
    return lines


def _parse_option_line(content: str) -> tuple[str, str, float]:
    """Parse ``# <unit> S <format> R <ohms>``; fields may come in any order."""
    frequency_unit, data_format, ref_impedance = "GHZ", "MA", 50.0
    tokens = iter(content[1:].upper().split())
    for token in tokens:
        if token in _FREQUENCY_SCALE:
            frequency_unit = token
        elif token in _DATA_FORMATS:
            data_format = token
        elif token == "R":
            ref_impedance = float(next(tokens, "nan"))
        elif token != "S":
            raise ValueError(f"only S-parameter files are supported; got {token}")
    if not ref_impedance > 0:
        raise ValueError(f"invalid reference impedance in {content!r}")
    return frequency_unit, data_format, ref_impedance


def _to_complex(first: NDArray, second: NDArray, data_format: str) -> NDArray:
    """Turn a pair of value columns into complex numbers."""
    if data_format == "RI":
        return first + 1j * second
    magnitude = first if data_format == "MA" else 10 ** (first / 20)
    return magnitude * np.exp(1j * np.deg2rad(second))
