"""Tests for the Touchstone reader and writer in ``simpleEMS.export_touchstone``.

The goldens ``tests/golden/touchstone_skrf_<P>port.s<P>p`` were written by
scikit-rf 1.9.0 from ``sample_s_matrix(P)`` below, back when simpleEMS
exported through it. The writer must reproduce them byte for byte, apart from
what only skrf does: its provenance line, and for 3+ ports its column-label
comments (a stray lone ``!`` line, and labels wrapped one pair off from the
data). Never regenerate the goldens to make a failing test pass.
"""

from pathlib import Path

import numpy as np
import pytest

from simpleEMS import __version__
from simpleEMS.export_touchstone import read_touchstone, write_touchstone

GOLDEN = Path(__file__).parent / "golden"
FREQS = np.linspace(1e9, 3e9, 7)
PORT_COUNTS = [1, 2, 3, 4, 5]
PORT_IDS = [f"{port_count}-port" for port_count in PORT_COUNTS]
PROVENANCE = (
    f"! Generated by simpleEMS {__version__} "
    "(https://github.com/MohamoudAli12/simpleEMS)."
)


def sample_s_matrix(port_count: int) -> np.ndarray:
    """The data the goldens were written from; keep in step with them."""
    rng = np.random.default_rng(port_count)
    shape = (FREQS.size, port_count, port_count)
    values = rng.uniform(-1, 1, shape) + 1j * rng.uniform(-1, 1, shape)
    if port_count > 1:
        values[:, 0, -1] = 0  # exact zeros, like the unsimulated S12
    values[0, 0, 0] = 1e-7 - 2.5e-12j  # small magnitudes print in exponent form
    return values


def golden_path(port_count: int) -> Path:
    return GOLDEN / f"touchstone_skrf_{port_count}port.s{port_count}p"


def comparable(path: Path, port_count: int) -> list[bytes]:
    """File lines minus what is unique to one writer."""
    lines = path.read_bytes().split(b"\n")
    lines = [
        line
        for line in lines
        if not line.startswith((b"! Created with skrf", b"! Generated by simpleEMS"))
    ]
    if port_count >= 3:
        lines = [line for line in lines if not line.startswith(b"!")]
    return lines


def write_text(tmp_path: Path, name: str, text: str) -> Path:
    path = tmp_path / name
    path.write_text(text)
    return path


# ---------------------------------------------------------------------
# Byte parity with the files scikit-rf used to write
# ---------------------------------------------------------------------
class TestMatchesScikitRf:
    @pytest.mark.parametrize("port_count", PORT_COUNTS, ids=PORT_IDS)
    def test_writer_reproduces_the_golden(self, tmp_path, port_count):
        path = write_touchstone(
            tmp_path / "new", FREQS, sample_s_matrix(port_count), ref_impedance=50
        )

        assert comparable(path, port_count) == comparable(
            golden_path(port_count), port_count
        )

    @pytest.mark.parametrize("port_count", PORT_COUNTS, ids=PORT_IDS)
    def test_reading_and_rewriting_the_golden_changes_no_bytes(
        self, tmp_path, port_count
    ):
        data = read_touchstone(golden_path(port_count))

        path = write_touchstone(
            tmp_path / "new",
            data.freqs,
            data.s_matrix,
            ref_impedance=data.ref_impedance,
        )

        assert comparable(path, port_count) == comparable(
            golden_path(port_count), port_count
        )

    @pytest.mark.parametrize("port_count", [1, 2], ids=["1-port", "2-port"])
    def test_column_labels_match_for_one_and_two_ports(self, tmp_path, port_count):
        path = write_touchstone(tmp_path / "new", FREQS, sample_s_matrix(port_count))

        new_labels = path.read_text().splitlines()[2]
        old_labels = golden_path(port_count).read_text().splitlines()[2]

        assert new_labels == old_labels


# ---------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------
class TestHeader:
    def test_first_line_credits_simpleems_and_links_the_repository(self, tmp_path):
        path = write_touchstone(tmp_path / "new", FREQS, sample_s_matrix(1))

        assert path.read_text().splitlines()[0] == PROVENANCE

    def test_option_line(self, tmp_path):
        path = write_touchstone(
            tmp_path / "new", FREQS, sample_s_matrix(1), ref_impedance=75
        )

        assert path.read_text().splitlines()[1] == "# Hz S RI R 75.0 "

    def test_comment_lines_come_first(self, tmp_path):
        path = write_touchstone(
            tmp_path / "new", FREQS, sample_s_matrix(1), comment="patch\nrun 3"
        )

        assert path.read_text().splitlines()[:3] == ["!patch", "!run 3", PROVENANCE]

    def test_four_port_labels_wrap_with_the_data(self, tmp_path):
        path = write_touchstone(tmp_path / "new", FREQS, sample_s_matrix(5))

        lines = path.read_text().splitlines()

        assert lines[2] == "!freq" + "".join(
            f" ReS1{column} ImS1{column}" for column in range(1, 5)
        )
        assert lines[3] == "! ReS15 ImS15"

    def test_line_endings_are_lf(self, tmp_path):
        path = write_touchstone(tmp_path / "new", FREQS, sample_s_matrix(2))

        assert b"\r" not in path.read_bytes()


# ---------------------------------------------------------------------
# Writer
# ---------------------------------------------------------------------
class TestWriter:
    def test_two_port_line_lists_s21_before_s12(self, tmp_path):
        matrix = np.array([[[1 + 0j, 12 + 0j], [21 + 0j, 22 + 0j]]])

        path = write_touchstone(tmp_path / "new", [1e9], matrix)

        assert path.read_text().splitlines()[-1] == (
            "1000000000.0 1.0 0.0 21.0 0.0 12.0 0.0 22.0 0.0"
        )

    def test_one_dimensional_input_is_a_one_port(self, tmp_path):
        path = write_touchstone(tmp_path / "new", FREQS, sample_s_matrix(1)[:, 0, 0])

        assert path.suffix == ".s1p"

    def test_extension_is_appended_and_directories_created(self, tmp_path):
        path = write_touchstone(
            tmp_path / "a" / "b" / "patch.v2", FREQS, sample_s_matrix(3)
        )

        assert path == tmp_path / "a" / "b" / "patch.v2.s3p"
        assert path.is_file()

    @pytest.mark.parametrize("port_count", PORT_COUNTS, ids=PORT_IDS)
    def test_round_trip(self, tmp_path, port_count):
        matrix = sample_s_matrix(port_count)

        path = write_touchstone(tmp_path / "new", FREQS, matrix, ref_impedance=75)
        data = read_touchstone(path)

        np.testing.assert_array_equal(data.freqs, FREQS)
        np.testing.assert_array_equal(data.s_matrix, matrix)
        assert data.ref_impedance == 75.0


# ---------------------------------------------------------------------
# Reader, on hand-written files
# ---------------------------------------------------------------------
class TestReader:
    def test_two_port_ma_puts_s21_and_s12_in_place(self, tmp_path):
        path = write_text(
            tmp_path,
            "two.s2p",
            "# MHZ S MA R 50\n100 0.1 0 0.2 90 0.3 180 0.4 -90\n",
        )

        data = read_touchstone(path)

        assert data.freqs == pytest.approx([100e6])
        assert data.s_matrix[0] == pytest.approx(
            np.array([[0.1, -0.3], [0.2j, -0.4j]]), abs=1e-12
        )

    @pytest.mark.parametrize(
        "record",
        [
            "# HZ S RI R 50\n1 0 0.5\n",
            "# HZ S MA R 50\n1 0.5 90\n",
            "# HZ S DB R 50\n1 -6.020599913279624 90\n",
        ],
        ids=["ri", "ma", "db"],
    )
    def test_formats_agree(self, tmp_path, record):
        data = read_touchstone(write_text(tmp_path, "one.s1p", record))

        assert data.s_matrix[0, 0, 0] == pytest.approx(0.5j, abs=1e-12)

    @pytest.mark.parametrize(
        ("unit", "scale"),
        [("HZ", 1.0), ("KHZ", 1e3), ("MHZ", 1e6), ("GHZ", 1e9)],
        ids=["hz", "khz", "mhz", "ghz"],
    )
    def test_frequency_units_scale_to_hertz(self, tmp_path, unit, scale):
        path = write_text(tmp_path, "one.s1p", f"# {unit} S RI R 50\n2.5 0 0\n")

        assert read_touchstone(path).freqs == pytest.approx([2.5 * scale])

    def test_bare_option_line_uses_the_spec_defaults(self, tmp_path):
        data = read_touchstone(write_text(tmp_path, "one.s1p", "#\n2 0.5 90\n"))

        assert data.freqs == pytest.approx([2e9])
        assert data.s_matrix[0, 0, 0] == pytest.approx(0.5j, abs=1e-12)
        assert data.ref_impedance == 50.0

    def test_comments_anywhere_are_ignored(self, tmp_path):
        path = write_text(
            tmp_path,
            "one.s1p",
            "! top\n# HZ S RI R 50 ! trailing\n1 0.1 0.2 ! inline\n! between\n"
            "2 0.3 0.4\n",
        )

        data = read_touchstone(path)

        assert data.s_matrix[:, 0, 0] == pytest.approx([0.1 + 0.2j, 0.3 + 0.4j])

    def test_irregular_line_breaks_still_parse(self, tmp_path):
        values = " ".join(str(number) for number in range(18))
        path = write_text(
            tmp_path, "three.s3p", f"# HZ S RI R 50\n1\n{values[:9]}\n{values[9:]}\n"
        )

        data = read_touchstone(path)

        assert data.s_matrix[0, 0, 1] == pytest.approx(2 + 3j)
        assert data.s_matrix[0, 2, 2] == pytest.approx(16 + 17j)

    def test_later_option_lines_are_ignored(self, tmp_path):
        path = write_text(
            tmp_path, "one.s1p", "# HZ S RI R 50\n# GHZ S MA R 75\n1 0.1 0.2\n"
        )

        data = read_touchstone(path)

        assert data.freqs == pytest.approx([1.0])
        assert data.ref_impedance == 50.0


# ---------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------
class TestErrors:
    @pytest.mark.parametrize(
        ("freqs", "matrix", "message"),
        [
            (FREQS, np.zeros((7, 2, 3)), "shape"),
            (FREQS[:3], np.zeros((7, 2, 2)), "frequencies"),
        ],
        ids=["non-square", "frequency-count-mismatch"],
    )
    def test_writer_rejects_bad_shapes(self, tmp_path, freqs, matrix, message):
        with pytest.raises(ValueError, match=message):
            write_touchstone(tmp_path / "new", freqs, matrix)

    @pytest.mark.parametrize("impedance", [0.0, -50.0], ids=["zero", "negative"])
    def test_writer_rejects_non_positive_impedance(self, tmp_path, impedance):
        with pytest.raises(ValueError, match="positive"):
            write_touchstone(
                tmp_path / "new", FREQS, sample_s_matrix(1), ref_impedance=impedance
            )

    @pytest.mark.parametrize(
        ("name", "text", "message"),
        [
            ("data.txt", "# HZ S RI R 50\n1 0 0\n", "sNp"),
            ("one.s1p", "[Version] 2.0\n# HZ S RI R 50\n1 0 0\n", "Touchstone 2"),
            ("one.s1p", "# HZ Y RI R 50\n1 0 0\n", "S-parameter"),
            ("two.s2p", "# HZ S RI R 50\n1 0 0 0 0\n", "whole"),
            ("one.s1p", "# HZ S RI R 50\n", "whole"),
        ],
        ids=["wrong-extension", "touchstone-2", "y-parameters", "truncated", "empty"],
    )
    def test_reader_rejects_bad_files(self, tmp_path, name, text, message):
        with pytest.raises(ValueError, match=message):
            read_touchstone(write_text(tmp_path, name, text))
