// Auto-generated by simpleEMS for 'structure'.
// E-field formulation, lumped resistive-sheet ports (reference Z0), mode-overlap S-parameters.

DefineConstant[
  FREQ = 2450000000.0,          // Hz (override per solve with -setnumber FREQ <f>)
  ACTIVE_PORT = 1,   // driven port for AnalysisSinglePort only
  FEorder = 1   // 1 (lowest-order Nedelec) or 2 (add BF_Edge_2E)
];
NbPorts = 1;
myDir = "output/";

eps0 = 8.8541878128e-12;
mu0  = 1.25663706212e-06;
c0   = 1/Sqrt[eps0*mu0];
Z0   = Sqrt[mu0/eps0];
eta0 = Z0;

Group {
  Diel_substrate = Region[100];
  Air  = Region[200];
  Pec  = Region[300];
  Port_1 = Region[401];



  Abc  = Region[500];

  Ports  = Region[{Port_1}];
  BndPEC = Region[{Pec}];
  DomainDiel = Region[{Diel_substrate}];
  Domain = Region[{Diel_substrate, Air}];
  BndAll = Region[{Pec, Ports, Abc}];
  TotAll = Region[{Domain, Ports, Abc}];
}

Function {
  I[] = Complex[0., 1.];
  epsR[Diel_substrate] = Complex[4.4, -0.0044];
  epsR[Air] = 1.;
  muR[] = 1.;

  nuR[Diel_substrate] = 1.0;
  nuR[Air] = 1.;
  k0[] = 2*Pi*FREQ / c0;


  dir_1[] = Vector[0., 0., 1.];
  ePort_1[] = dir_1[];
  Yrel_1 = eta0 / (93.74999999999999);  // eta0/Zs, Zs=z0*w/gap
  eInc[Port_1] = ($ActivePort == 1) ? ePort_1[] : Vector[0.,0.,0.];
  eInc[Abc] = Vector[0.,0.,0.];
}

Jacobian {
  { Name Jac ; Case {
    { Region BndAll ; Jacobian Sur ; }
    { Region Domain ; Jacobian Vol ; }
  } }
}

Integration {
  { Name I1 ; Case { { Type Gauss ; Case {
    { GeoElement Point ; NumberOfPoints 1 ; }
    { GeoElement Line ; NumberOfPoints 4 ; }
    { GeoElement Triangle ; NumberOfPoints 7 ; }
    { GeoElement Tetrahedron ; NumberOfPoints 15 ; }
  } } } }
}

Constraint {
  { Name ElectricField ; Case { { Region BndPEC ; Value 0. ; } } }
}

FunctionSpace {
  { Name eSpace ; Type Form1 ;
    BasisFunction {
      { Name sn ; NameOfCoef en ; Function BF_Edge ; Support TotAll ; Entity EdgesOf[All] ; }
      If (FEorder == 2)
        { Name sn2 ; NameOfCoef en2 ; Function BF_Edge_2E ; Support TotAll ; Entity EdgesOf[All] ; }
      EndIf
    }
    Constraint {
      { NameOfCoef en ; EntityType EdgesOf ; NameOfConstraint ElectricField ; }
      If (FEorder == 2)
        { NameOfCoef en2 ; EntityType EdgesOf ; NameOfConstraint ElectricField ; }
      EndIf
    }
  }
}

Formulation {
  { Name eFormulation ; Type FemEquation ;
    Quantity { { Name e ; Type Local ; NameOfSpace eSpace ; } }
    Equation {
      // curl-curl "stiffness" term: nuR * (curl E)·(curl w)  [d e = curl e]
      Galerkin { [ nuR[] * Dof{d e} , {d e} ] ;
        In Domain ; Integration I1 ; Jacobian Jac ; }
      // "mass" term: -k0^2 * epsR * E·w  (together they are the wave equation)
      Galerkin { [ -k0[]^2 * epsR[] * Dof{e} , {e} ] ;
        In Domain ; Integration I1 ; Jacobian Jac ; }

      // outer free-space Silver-Muller ABC (first-order outgoing-wave boundary)
      Galerkin { [ -I[]*k0[] * (1/muR[]) * Normal[] /\ ( Normal[] /\ Dof{e} ) , {e} ] ;
        In Abc ; Integration I1 ; Jacobian Jac ; }


      // lumped port 1: resistive sheet (Z0=50.0) + source
      Galerkin { [ -I[]*k0[]*Yrel_1*(1/muR[]) * Normal[] /\ (Normal[] /\ Dof{e}) , {e} ] ;
        In Port_1 ; Integration I1 ; Jacobian Jac ; }
      Galerkin { [ 2*I[]*k0[]*Yrel_1*(1/muR[]) * Normal[] /\ (Normal[] /\ eInc[]) , {e} ] ;
        In Port_1 ; Integration I1 ; Jacobian Jac ; }
    }
  }
}

Resolution {
  // All ports at one frequency, in a single launch: assemble + factorise once,
  // then only the right-hand side is rebuilt per port (see above).
  { Name Analysis ;
    System { { Name A ; NameOfFormulation eFormulation ; Type ComplexValue ; Frequency FREQ ; } }
    Operation {
      CreateDir[Str[myDir]] ;
      Evaluate[ $ActivePort = 1 ] ;
      Generate[A] ; Solve[A] ;
      PostOperation[Get_SParameters] ;
    }
  }
  // One port only, driven by the ACTIVE_PORT constant, keeping the solution for
  // a follow-up -pos run. Used by fem_solver.solve_fields_and_power, which
  // wants the field views at a single driven port rather than an S-matrix.
  { Name AnalysisSinglePort ;
    System { { Name A ; NameOfFormulation eFormulation ; Type ComplexValue ; Frequency FREQ ; } }
    Operation {
      CreateDir[Str[myDir]] ;
      Evaluate[ $ActivePort = ACTIVE_PORT ] ;
      Generate[A] ; Solve[A] ; SaveSolution[A] ;
    }
  }
}

PostProcessing {
  { Name postPro ; NameOfFormulation eFormulation ;
    Quantity {
        { Name intPort_1 ;
          Value { Integral { [ (ePort_1[]*dir_1[]) * (ePort_1[]*dir_1[]) ] ;
            In Port_1 ; Jacobian Jac ; Integration I1 ; } } }
        { Name xS_1 ;
          Value { Integral { [ (({e}*dir_1[]) - (($ActivePort == 1) ? (ePort_1[]*dir_1[]) : 0)) * (ePort_1[]*dir_1[]) / #(1) ] ;
            In Port_1 ; Jacobian Jac ; Integration I1 ; } } }
        { Name V_1 ;
          Value { Integral { [ 0.0016 * ({e}*dir_1[]) / #(1) ] ;
            In Port_1 ; Jacobian Jac ; Integration I1 ; } } }
        { Name I_1 ;
          Value { Integral { [ (0.0016/50.0) * (2*(eInc[]*dir_1[]) - ({e}*dir_1[])) / #(1) ] ;
            In Port_1 ; Jacobian Jac ; Integration I1 ; } } }
      { Name e ; Value { Local { [ {e} ] ; In Domain ; Jacobian Jac ; } } }
      { Name h ; Value { Local { [ I[]*(1/muR[])*{d e}/(k0[]*eta0) ] ; In Domain ; Jacobian Jac ; } } }
      // dielectric loss  P = (1/2) w eps0 Im[epsR] |E|^2  integrated over the volume.
      // Over DomainDiel, not Domain: in the PML epsR is a TensorDiag, so the
      // integrand there is a tensor rather than a scalar (and the PML's
      // absorption is not dielectric loss anyway). Air is lossless, so
      // dropping it too costs nothing.
      { Name Ploss ; Value { Integral { [ -Pi*FREQ*eps0*Im[epsR[]]*SquNorm[{e}] ] ;
        In DomainDiel ; Jacobian Jac ; Integration I1 ; } } }
      // conductor loss, one quantity per distinct sheet conductivity

    }
  }
}

PostOperation {
  { Name Get_SParameters ; NameOfPostProcessing postPro ;
    Operation {
      Print [ intPort_1[Port_1], OnRegion Port_1, StoreInRegister (1),
        Format Table, File > StrCat[myDir, "intPort.txt"] ];
      Print [ xS_1[Port_1], OnRegion Port_1, Format Table,
        File > StrCat[myDir, "xS_1.txt"] ];
      Print [ V_1[Port_1], OnRegion Port_1, Format Table,
        File > StrCat[myDir, "V_1.txt"] ];
      Print [ I_1[Port_1], OnRegion Port_1, Format Table,
        File > StrCat[myDir, "I_1.txt"] ];
    }
  }
  { Name Get_Fields ; NameOfPostProcessing postPro ;
    Operation {
      Print [ e, OnElementsOf Domain, File StrCat[myDir, "e.pos"] ] ;
      Print [ h, OnElementsOf Domain, File StrCat[myDir, "h.pos"] ] ;
    }
  }
  { Name Get_Power ; NameOfPostProcessing postPro ;
    Operation {
      Print [ Ploss[DomainDiel], OnGlobal, Format Table, File > StrCat[myDir, "Ploss.txt"] ] ;

      Print [ intPort_1[Port_1], OnRegion Port_1, StoreInRegister (1),
        Format Table, File > StrCat[myDir, "intPort.txt"] ] ;
      Print [ V_1[Port_1], OnRegion Port_1, Format Table,
        File > StrCat[myDir, "Vdrv_1.txt"] ] ;
      Print [ I_1[Port_1], OnRegion Port_1, Format Table,
        File > StrCat[myDir, "Idrv_1.txt"] ] ;
    }
  }
}
